server:
  port: 8086

spring:
  application:
    name: ms-logros
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/db_logros?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

ms:
  usuarios:
    url: http://localhost:8081
  juegos:
    url: http://localhost:8082
  biblioteca:
    url: http://localhost:8083

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true